name: SFML_CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsfml-dev
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j4

  build_linux_static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsfml-dev libegl1-mesa libgl1-mesa-dev libglu1-mesa libglu1-mesa-dev libsfml-dev libgtest-dev binutils-dev libtool lua5.2 liblua5.2-dev liblua5.2-0 graphviz doxygen
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=TRUE ..
        make -j4

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        brew install sfml
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j4
        
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        vcpkg install sfml
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build .
