name: SFML_CI

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsfml-dev
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j4

  build_linux_static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt-get install -y libpthread-stubs0-dev libgl1-mesa-dev libx11-dev libxrandr-dev libfreetype6-dev libglew1.5-dev libjpeg8-dev
        sudo apt-get install -y libsndfile1-dev libopenal-dev libudev-dev libxcb-image0-dev libjpeg-dev libflac-dev libx11-xcb-dev libxcb-randr0
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_STATIC=TRUE ..
        make -j4

  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        brew install sfml
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j4
        
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Install dependencies
      run: |
        vcpkg install sfml
        
    - name: Build
      run: |
        mkdir build/ && cd build/
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
        cmake --build .
